/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_productcomponentsoss_componenttype = {
  124860000: '124860000',
  124860001: '124860001',
  124860002: '124860002',
  124860003: '124860003',
  124860004: '124860004'
} as const;
export type Oss_productcomponentsoss_componenttype = keyof typeof Oss_productcomponentsoss_componenttype;
export const Oss_productcomponentsoss_componenttypev2 = {
  124860000: 'Solution',
  124860001: 'App',
  124860002: 'Flow',
  124860003: 'CustomConnector',
  124860004: 'ConnectionReference',
  124860005: 'EnvironmentVariable',
  124860006: 'SecurityRole',
  124860007: 'DataverseTable'
} as const;
export type Oss_productcomponentsoss_componenttypev2 = keyof typeof Oss_productcomponentsoss_componenttypev2;
export const Oss_productcomponentsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_productcomponentsstatecode = keyof typeof Oss_productcomponentsstatecode;
export const Oss_productcomponentsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_productcomponentsstatuscode = keyof typeof Oss_productcomponentsstatuscode;

export interface Oss_productcomponentsBase {
  importsequencenumber?: number;
  oss_canonicalkey?: string;
  oss_componentlabel?: string;
  oss_componenttype?: Oss_productcomponentsoss_componenttype;
  oss_componenttypev2?: Oss_productcomponentsoss_componenttypev2;
  oss_hybridowned?: boolean;
  oss_hybridowneremail?: string;
  oss_hybridownername?: string;
  oss_name?: string;
  "oss_Product@odata.bind": string;
  oss_productcomponentid: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_productcomponentsstatecode;
  statuscode?: Oss_productcomponentsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_productcomponents extends Oss_productcomponentsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_componenttypename?: string;
  oss_componenttypev2name?: string;
  oss_hybridownedname?: string;
  oss_productname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_product?: object;
  _oss_product_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}