/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_enhancementsoss_priority = {
  124860000: 'High',
  124860001: 'Medium',
  124860002: 'Low',
  124860003: 'TBD'
} as const;
export type Oss_enhancementsoss_priority = keyof typeof Oss_enhancementsoss_priority;
export const Oss_enhancementsoss_status = {
  124860000: 'Backlog',
  124860001: 'InProgress',
  124860002: 'Completed',
  124860003: 'Cancelled'
} as const;
export type Oss_enhancementsoss_status = keyof typeof Oss_enhancementsoss_status;
export const Oss_enhancementsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_enhancementsstatecode = keyof typeof Oss_enhancementsstatecode;
export const Oss_enhancementsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_enhancementsstatuscode = keyof typeof Oss_enhancementsstatuscode;

export interface Oss_enhancementsBase {
  importsequencenumber?: number;
  oss_description?: string;
  oss_enhancementid: string;
  oss_levelofeffort?: number;
  oss_name?: string;
  oss_primarydeveloperemail?: string;
  oss_primarydevelopername?: string;
  oss_priority?: Oss_enhancementsoss_priority;
  "oss_Product@odata.bind": string;
  oss_secondarydeveloperemail?: string;
  oss_secondarydevelopername?: string;
  oss_solution?: string;
  oss_solutionlink?: string;
  oss_status?: Oss_enhancementsoss_status;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_enhancementsstatecode;
  statuscode?: Oss_enhancementsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_enhancements extends Oss_enhancementsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_priorityname?: string;
  oss_productname?: string;
  oss_statusname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_product?: object;
  _oss_product_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}