/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_reviewchecklisttemplatesstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_reviewchecklisttemplatesstatecode = keyof typeof Oss_reviewchecklisttemplatesstatecode;
export const Oss_reviewchecklisttemplatesstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_reviewchecklisttemplatesstatuscode = keyof typeof Oss_reviewchecklisttemplatesstatuscode;

export interface Oss_reviewchecklisttemplatesBase {
  importsequencenumber?: number;
  oss_isactive?: boolean;
  oss_name?: string;
  oss_reviewchecklisttemplateid: string;
  oss_sortorder?: number;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_reviewchecklisttemplatesstatecode;
  statuscode?: Oss_reviewchecklisttemplatesstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_reviewchecklisttemplates extends Oss_reviewchecklisttemplatesBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_isactivename?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}