/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_invconnectionreferencesoss_capturepath = {
  124860000: 'Import',
  124860001: 'Refresh'
} as const;
export type Oss_invconnectionreferencesoss_capturepath = keyof typeof Oss_invconnectionreferencesoss_capturepath;
export const Oss_invconnectionreferencesstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_invconnectionreferencesstatecode = keyof typeof Oss_invconnectionreferencesstatecode;
export const Oss_invconnectionreferencesstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_invconnectionreferencesstatuscode = keyof typeof Oss_invconnectionreferencesstatuscode;

export interface Oss_invconnectionreferencesBase {
  importsequencenumber?: number;
  oss_canonicalkey?: string;
  oss_capturedbyemail?: string;
  oss_capturedbyname?: string;
  oss_capturedon?: string;
  oss_capturepath?: Oss_invconnectionreferencesoss_capturepath;
  oss_connectionid?: string;
  oss_connector?: string;
  oss_connrefkey?: string;
  oss_displayname?: string;
  "oss_Environment@odata.bind"?: string;
  oss_environmentid?: string;
  oss_firstseenon?: string;
  oss_insolution?: boolean;
  oss_invconnectionreferenceid: string;
  oss_isbound?: boolean;
  oss_logicalname?: string;
  oss_missingsince?: string;
  oss_name?: string;
  oss_objectid?: string;
  oss_solutionname?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_invconnectionreferencesstatecode;
  statuscode?: Oss_invconnectionreferencesstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_invconnectionreferences extends Oss_invconnectionreferencesBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_capturepathname?: string;
  oss_environmentname?: string;
  oss_insolutionname?: string;
  oss_isboundname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_environment?: object;
  _oss_environment_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}