/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_environmentsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_environmentsstatecode = keyof typeof Oss_environmentsstatecode;
export const Oss_environmentsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_environmentsstatuscode = keyof typeof Oss_environmentsstatuscode;

export interface Oss_environmentsBase {
  importsequencenumber?: number;
  oss_environmentguid?: string;
  oss_environmentid: string;
  oss_isteamowned?: boolean;
  oss_name?: string;
  "oss_Pipeline@odata.bind"?: string;
  oss_promotionorder?: number;
  oss_sku?: string;
  oss_sortorder?: number;
  oss_url?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_environmentsstatecode;
  statuscode?: Oss_environmentsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_environments extends Oss_environmentsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_isteamownedname?: string;
  oss_pipelinename?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_pipeline?: object;
  _oss_pipeline_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}