/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_statushistoriesoss_itemtype = {
  124860000: 'Enhancement',
  124860001: 'CodeReview'
} as const;
export type Oss_statushistoriesoss_itemtype = keyof typeof Oss_statushistoriesoss_itemtype;
export const Oss_statushistoriesstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_statushistoriesstatecode = keyof typeof Oss_statushistoriesstatecode;
export const Oss_statushistoriesstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_statushistoriesstatuscode = keyof typeof Oss_statushistoriesstatuscode;

export interface Oss_statushistoriesBase {
  importsequencenumber?: number;
  oss_changedbyemail?: string;
  oss_changedbyname?: string;
  "oss_CodeReview@odata.bind"?: string;
  "oss_Enhancement@odata.bind"?: string;
  oss_fromstatus?: number;
  oss_fromstatuslabel?: string;
  oss_itemtype?: Oss_statushistoriesoss_itemtype;
  oss_name?: string;
  oss_note?: string;
  oss_statushistoryid: string;
  oss_tostatus?: number;
  oss_tostatuslabel?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_statushistoriesstatecode;
  statuscode?: Oss_statushistoriesstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_statushistories extends Oss_statushistoriesBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_codereviewname?: string;
  oss_enhancementname?: string;
  oss_itemtypename?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_codereview?: object;
  _oss_codereview_value?: string;
  oss_enhancement?: object;
  _oss_enhancement_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}