/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_invcustomconnectorsoss_capturepath = {
  124860000: 'Import',
  124860001: 'Refresh'
} as const;
export type Oss_invcustomconnectorsoss_capturepath = keyof typeof Oss_invcustomconnectorsoss_capturepath;
export const Oss_invcustomconnectorsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_invcustomconnectorsstatecode = keyof typeof Oss_invcustomconnectorsstatecode;
export const Oss_invcustomconnectorsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_invcustomconnectorsstatuscode = keyof typeof Oss_invcustomconnectorsstatuscode;

export interface Oss_invcustomconnectorsBase {
  importsequencenumber?: number;
  oss_canonicalkey?: string;
  oss_capturedbyemail?: string;
  oss_capturedbyname?: string;
  oss_capturedon?: string;
  oss_capturepath?: Oss_invcustomconnectorsoss_capturepath;
  oss_connectortype?: string;
  oss_displayname?: string;
  "oss_Environment@odata.bind"?: string;
  oss_environmentid?: string;
  oss_firstseenon?: string;
  oss_insolution?: boolean;
  oss_invcustomconnectorid: string;
  oss_ismanaged?: boolean;
  oss_missingsince?: string;
  oss_name: string;
  oss_objectid?: string;
  oss_ownername?: string;
  oss_solutionname?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_invcustomconnectorsstatecode;
  statuscode?: Oss_invcustomconnectorsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_invcustomconnectors extends Oss_invcustomconnectorsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_capturepathname?: string;
  oss_environmentname?: string;
  oss_insolutionname?: string;
  oss_ismanagedname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_environment?: object;
  _oss_environment_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}