/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_findingdismissalsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_findingdismissalsstatecode = keyof typeof Oss_findingdismissalsstatecode;
export const Oss_findingdismissalsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_findingdismissalsstatuscode = keyof typeof Oss_findingdismissalsstatuscode;

export interface Oss_findingdismissalsBase {
  importsequencenumber?: number;
  oss_canonicalkey?: string;
  oss_category?: string;
  oss_dismissedbyemail?: string;
  oss_dismissedbyname?: string;
  oss_dismissedon?: string;
  oss_environmentid?: string;
  oss_findingdismissalid: string;
  oss_findingkey?: string;
  oss_name: string;
  oss_reason?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_findingdismissalsstatecode;
  statuscode?: Oss_findingdismissalsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_findingdismissals extends Oss_findingdismissalsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}