/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_reviewcommentsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_reviewcommentsstatecode = keyof typeof Oss_reviewcommentsstatecode;
export const Oss_reviewcommentsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_reviewcommentsstatuscode = keyof typeof Oss_reviewcommentsstatuscode;

export interface Oss_reviewcommentsBase {
  importsequencenumber?: number;
  oss_author_email?: string;
  oss_author_name?: string;
  oss_body?: string;
  "oss_Code_Review@odata.bind"?: string;
  oss_name?: string;
  oss_reviewcommentid: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_reviewcommentsstatecode;
  statuscode?: Oss_reviewcommentsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_reviewcomments extends Oss_reviewcommentsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_code_reviewname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_code_review?: object;
  _oss_code_review_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}