/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_productsoss_lifecyclestate = {
  124860000: '_124860000',
  124860001: '_124860001',
  124860002: '_124860002'
} as const;
export type Oss_productsoss_lifecyclestate = keyof typeof Oss_productsoss_lifecyclestate;
export const Oss_productsoss_userscope = {
  124860000: 'Internal',
  124860001: 'SmallTeam__50Users_',
  124860002: 'Enterprise'
} as const;
export type Oss_productsoss_userscope = keyof typeof Oss_productsoss_userscope;
export const Oss_productsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_productsstatecode = keyof typeof Oss_productsstatecode;
export const Oss_productsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_productsstatuscode = keyof typeof Oss_productsstatuscode;

export interface Oss_productsBase {
  importsequencenumber?: number;
  oss_businessowneremail?: string;
  oss_businessownername?: string;
  oss_description?: string;
  oss_docs?: string;
  oss_docsmodifiedbyemail?: string;
  oss_docsmodifiedbyname?: string;
  oss_docsmodifiedon?: string;
  oss_lifecycledate?: string;
  oss_lifecyclereason?: string;
  oss_lifecyclestate?: Oss_productsoss_lifecyclestate;
  oss_name?: string;
  oss_primarydeveloperemail?: string;
  oss_primarydevelopername?: string;
  oss_productcode?: string;
  oss_productid: string;
  oss_secondarydeveloperemail?: string;
  oss_secondarydevelopername?: string;
  "oss_SupersededBy@odata.bind"?: string;
  oss_technicalowneremail?: string;
  oss_technicalownername?: string;
  oss_userscope?: Oss_productsoss_userscope;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_productsstatecode;
  statuscode?: Oss_productsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_products extends Oss_productsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_lifecyclestatename?: string;
  oss_supersededbyname?: string;
  oss_userscopename?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_supersededby?: object;
  _oss_supersededby_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}