/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_invflowsoss_capturepath = {
  124860000: 'Import',
  124860001: 'Refresh'
} as const;
export type Oss_invflowsoss_capturepath = keyof typeof Oss_invflowsoss_capturepath;
export const Oss_invflowsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_invflowsstatecode = keyof typeof Oss_invflowsstatecode;
export const Oss_invflowsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_invflowsstatuscode = keyof typeof Oss_invflowsstatuscode;

export interface Oss_invflowsBase {
  importsequencenumber?: number;
  oss_canonicalkey?: string;
  oss_capturedbyemail?: string;
  oss_capturedbyname?: string;
  oss_capturedon?: string;
  oss_capturepath?: Oss_invflowsoss_capturepath;
  oss_category?: string;
  "oss_Environment@odata.bind"?: string;
  oss_environmentid?: string;
  oss_firstseenon?: string;
  oss_insolution?: boolean;
  oss_invflowid: string;
  oss_lastrunon?: string;
  oss_missingsince?: string;
  oss_name?: string;
  oss_objectid?: string;
  oss_owneremail?: string;
  oss_ownername?: string;
  oss_primaryentity?: string;
  oss_solutionname?: string;
  oss_state?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_invflowsstatecode;
  statuscode?: Oss_invflowsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_invflows extends Oss_invflowsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_capturepathname?: string;
  oss_environmentname?: string;
  oss_insolutionname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_environment?: object;
  _oss_environment_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}