/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_refreshrunsoss_scope = {
  124860000: 'SingleEnvironment',
  124860001: 'AllEnvironments'
} as const;
export type Oss_refreshrunsoss_scope = keyof typeof Oss_refreshrunsoss_scope;
export const Oss_refreshrunsoss_status = {
  124860000: 'Running',
  124860001: 'Completed',
  124860002: 'Partial',
  124860003: 'Failed'
} as const;
export type Oss_refreshrunsoss_status = keyof typeof Oss_refreshrunsoss_status;
export const Oss_refreshrunsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_refreshrunsstatecode = keyof typeof Oss_refreshrunsstatecode;
export const Oss_refreshrunsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_refreshrunsstatuscode = keyof typeof Oss_refreshrunsstatuscode;

export interface Oss_refreshrunsBase {
  importsequencenumber?: number;
  oss_completedon?: string;
  oss_errorcount?: number;
  oss_missingcount?: number;
  oss_name?: string;
  oss_refreshrunid: string;
  oss_runbyemail?: string;
  oss_runbyname?: string;
  oss_scope?: Oss_refreshrunsoss_scope;
  oss_scopeenvironmentid?: string;
  oss_startedon?: string;
  oss_status?: Oss_refreshrunsoss_status;
  oss_upsertedcount?: number;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_refreshrunsstatecode;
  statuscode?: Oss_refreshrunsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_refreshruns extends Oss_refreshrunsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_scopename?: string;
  oss_statusname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}