/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_refreshrununitsoss_objecttype = {
  124860000: '124860000',
  124860001: '124860001',
  124860002: '124860002',
  124860003: '124860003',
  124860004: '124860004'
} as const;
export type Oss_refreshrununitsoss_objecttype = keyof typeof Oss_refreshrununitsoss_objecttype;
export const Oss_refreshrununitsoss_objecttypev2 = {
  124860000: 'Solution',
  124860001: 'App',
  124860002: 'Flow',
  124860003: 'CustomConnector',
  124860004: 'ConnectionReference',
  124860005: 'EnvironmentVariable',
  124860006: 'SecurityRole',
  124860007: 'DataverseTable'
} as const;
export type Oss_refreshrununitsoss_objecttypev2 = keyof typeof Oss_refreshrununitsoss_objecttypev2;
export const Oss_refreshrununitsoss_status = {
  124860000: '124860000',
  124860001: '124860001',
  124860002: '124860002',
  124860003: '124860003'
} as const;
export type Oss_refreshrununitsoss_status = keyof typeof Oss_refreshrununitsoss_status;
export const Oss_refreshrununitsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_refreshrununitsstatecode = keyof typeof Oss_refreshrununitsstatecode;
export const Oss_refreshrununitsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_refreshrununitsstatuscode = keyof typeof Oss_refreshrununitsstatuscode;

export interface Oss_refreshrununitsBase {
  importsequencenumber?: number;
  oss_environmentid?: string;
  oss_errorcount?: number;
  oss_errormessage?: string;
  oss_fetchedcount?: number;
  oss_lastattemptedon?: string;
  oss_missingcount?: number;
  oss_name?: string;
  oss_objecttype?: Oss_refreshrununitsoss_objecttype;
  oss_objecttypev2?: Oss_refreshrununitsoss_objecttypev2;
  "oss_RefreshRun@odata.bind": string;
  oss_refreshrununitid: string;
  oss_status?: Oss_refreshrununitsoss_status;
  oss_upsertedcount?: number;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_refreshrununitsstatecode;
  statuscode?: Oss_refreshrununitsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_refreshrununits extends Oss_refreshrununitsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_objecttypename?: string;
  oss_objecttypev2name?: string;
  oss_refreshrunname?: string;
  oss_statusname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_refreshrun?: object;
  _oss_refreshrun_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}