/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_reviewchecklistitemsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_reviewchecklistitemsstatecode = keyof typeof Oss_reviewchecklistitemsstatecode;
export const Oss_reviewchecklistitemsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_reviewchecklistitemsstatuscode = keyof typeof Oss_reviewchecklistitemsstatuscode;

export interface Oss_reviewchecklistitemsBase {
  importsequencenumber?: number;
  "oss_CodeReview@odata.bind": string;
  oss_ischecked?: boolean;
  oss_name?: string;
  oss_not_applicable?: boolean;
  oss_reviewchecklistitemid: string;
  oss_sortorder?: number;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_reviewchecklistitemsstatecode;
  statuscode?: Oss_reviewchecklistitemsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_reviewchecklistitems extends Oss_reviewchecklistitemsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_codereviewname?: string;
  oss_ischeckedname?: string;
  oss_not_applicablename?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_codereview?: object;
  _oss_codereview_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}