/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_invappsoss_capturepath = {
  124860000: '124860000',
  124860001: '124860001'
} as const;
export type Oss_invappsoss_capturepath = keyof typeof Oss_invappsoss_capturepath;
export const Oss_invappsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_invappsstatecode = keyof typeof Oss_invappsstatecode;
export const Oss_invappsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_invappsstatuscode = keyof typeof Oss_invappsstatuscode;

export interface Oss_invappsBase {
  importsequencenumber?: number;
  oss_apptype?: string;
  oss_canonicalkey?: string;
  oss_capturedbyemail?: string;
  oss_capturedbyname?: string;
  oss_capturedon?: string;
  oss_capturepath?: Oss_invappsoss_capturepath;
  oss_connectorrefcount?: number;
  oss_connectorrefs?: string;
  "oss_Environment@odata.bind"?: string;
  oss_environmentid?: string;
  oss_firstseenon?: string;
  oss_insolution?: boolean;
  oss_invappid: string;
  oss_lastlaunchedon?: string;
  oss_lastpublishedon?: string;
  oss_missingsince?: string;
  oss_name?: string;
  oss_objectid?: string;
  oss_openuri?: string;
  oss_owneremail?: string;
  oss_ownername?: string;
  oss_sharedgroupscount?: number;
  oss_shareduserscount?: number;
  oss_solutionname?: string;
  oss_status?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_invappsstatecode;
  statuscode?: Oss_invappsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_invapps extends Oss_invappsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_capturepathname?: string;
  oss_environmentname?: string;
  oss_insolutionname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_environment?: object;
  _oss_environment_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}