/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_deploymentrunsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_deploymentrunsstatecode = keyof typeof Oss_deploymentrunsstatecode;
export const Oss_deploymentrunsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_deploymentrunsstatuscode = keyof typeof Oss_deploymentrunsstatuscode;

export interface Oss_deploymentrunsBase {
  importsequencenumber?: number;
  oss_approverupn?: string;
  oss_deploymentrunid: string;
  oss_externalrunlink?: string;
  oss_name?: string;
  oss_outcomerecordedon?: string;
  oss_requestedon?: string;
  oss_requesterupn?: string;
  oss_solutionname?: string;
  oss_solutionversion?: string;
  oss_sourceenvid?: string;
  oss_status?: string;
  oss_targetenvid?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_deploymentrunsstatecode;
  statuscode?: Oss_deploymentrunsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_deploymentruns extends Oss_deploymentrunsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}