/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_deploymentprofilesstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_deploymentprofilesstatecode = keyof typeof Oss_deploymentprofilesstatecode;
export const Oss_deploymentprofilesstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_deploymentprofilesstatuscode = keyof typeof Oss_deploymentprofilesstatuscode;

export interface Oss_deploymentprofilesBase {
  importsequencenumber?: number;
  oss_deploymentprofileid: string;
  oss_name?: string;
  oss_notes?: string;
  oss_serviceaccountname?: string;
  oss_serviceaccountupn?: string;
  oss_solutionid?: string;
  oss_solutionname?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_deploymentprofilesstatecode;
  statuscode?: Oss_deploymentprofilesstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_deploymentprofiles extends Oss_deploymentprofilesBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}