/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_metricdailiesoss_capturepath = {
  124860000: 'Import',
  124860001: 'Refresh'
} as const;
export type Oss_metricdailiesoss_capturepath = keyof typeof Oss_metricdailiesoss_capturepath;
export const Oss_metricdailiesoss_metrictype = {
  124860000: 'FlowRunLastRun',
  124860001: 'LastLaunched',
  124860002: 'LaunchCount',
  124860003: 'UniqueUsers',
  124860004: 'FlowRuns',
  124860005: 'FlowSuccessRate'
} as const;
export type Oss_metricdailiesoss_metrictype = keyof typeof Oss_metricdailiesoss_metrictype;
export const Oss_metricdailiesoss_objecttype = {
  124860000: 'App',
  124860001: 'Flow'
} as const;
export type Oss_metricdailiesoss_objecttype = keyof typeof Oss_metricdailiesoss_objecttype;
export const Oss_metricdailiesstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_metricdailiesstatecode = keyof typeof Oss_metricdailiesstatecode;
export const Oss_metricdailiesstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_metricdailiesstatuscode = keyof typeof Oss_metricdailiesstatuscode;

export interface Oss_metricdailiesBase {
  importsequencenumber?: number;
  oss_capturedate?: string;
  oss_capturedbyemail?: string;
  oss_capturedbyname?: string;
  oss_capturepath?: Oss_metricdailiesoss_capturepath;
  "oss_Environment@odata.bind"?: string;
  oss_environmentid?: string;
  oss_metricdailyid: string;
  oss_metrictype?: Oss_metricdailiesoss_metrictype;
  oss_name?: string;
  oss_objectid?: string;
  oss_objecttype?: Oss_metricdailiesoss_objecttype;
  oss_valuedatetime?: string;
  oss_valuenumeric?: number;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_metricdailiesstatecode;
  statuscode?: Oss_metricdailiesstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_metricdailies extends Oss_metricdailiesBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_capturepathname?: string;
  oss_environmentname?: string;
  oss_metrictypename?: string;
  oss_objecttypename?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_environment?: object;
  _oss_environment_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}