/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_deploymentbindingsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_deploymentbindingsstatecode = keyof typeof Oss_deploymentbindingsstatecode;
export const Oss_deploymentbindingsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_deploymentbindingsstatuscode = keyof typeof Oss_deploymentbindingsstatuscode;

export interface Oss_deploymentbindingsBase {
  importsequencenumber?: number;
  oss_apiid?: string;
  oss_canonicalkey?: string;
  oss_connectionid?: string;
  oss_connectorname?: string;
  oss_deploymentbindingid: string;
  "oss_DeploymentRun@odata.bind"?: string;
  oss_name?: string;
  oss_ownerupn?: string;
  oss_referencelogicalname?: string;
  oss_resolvedstatus?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_deploymentbindingsstatecode;
  statuscode?: Oss_deploymentbindingsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_deploymentbindings extends Oss_deploymentbindingsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_deploymentrunname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_deploymentrun?: object;
  _oss_deploymentrun_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}