/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_codereviewsoss_changetype = {
  124860000: 'Enhancement',
  124860001: 'NewSolution',
  124860002: 'BugFix',
  124860003: 'EmergencyFix'
} as const;
export type Oss_codereviewsoss_changetype = keyof typeof Oss_codereviewsoss_changetype;
export const Oss_codereviewsoss_status = {
  124860000: 'Requested',
  124860001: 'InReview',
  124860002: 'Approved',
  124860003: 'ChangesRequested',
  124860004: 'Rejected'
} as const;
export type Oss_codereviewsoss_status = keyof typeof Oss_codereviewsoss_status;
export const Oss_codereviewsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_codereviewsstatecode = keyof typeof Oss_codereviewsstatecode;
export const Oss_codereviewsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_codereviewsstatuscode = keyof typeof Oss_codereviewsstatuscode;

export interface Oss_codereviewsBase {
  importsequencenumber?: number;
  oss_changetype?: Oss_codereviewsoss_changetype;
  oss_codereviewid: string;
  oss_developeremail?: string;
  oss_developername?: string;
  "oss_Enhancement@odata.bind"?: string;
  "oss_Environment@odata.bind"?: string;
  oss_name?: string;
  oss_primaryrevieweremail?: string;
  oss_primaryreviewername?: string;
  "oss_Product@odata.bind": string;
  oss_relatedticketlink?: string;
  oss_requestedpushdate?: string;
  oss_solution?: string;
  oss_solutionversion?: string;
  oss_status?: Oss_codereviewsoss_status;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_codereviewsstatecode;
  statuscode?: Oss_codereviewsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_codereviews extends Oss_codereviewsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_changetypename?: string;
  oss_enhancementname?: string;
  oss_environmentname?: string;
  oss_productname?: string;
  oss_statusname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  oss_enhancement?: object;
  _oss_enhancement_value?: string;
  oss_environment?: object;
  _oss_environment_value?: string;
  oss_product?: object;
  _oss_product_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}