/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_connectioncatalogsstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_connectioncatalogsstatecode = keyof typeof Oss_connectioncatalogsstatecode;
export const Oss_connectioncatalogsstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_connectioncatalogsstatuscode = keyof typeof Oss_connectioncatalogsstatuscode;

export interface Oss_connectioncatalogsBase {
  importsequencenumber?: number;
  oss_apiid?: string;
  oss_authtype?: string;
  oss_canonicalkey?: string;
  oss_capturepath?: string;
  oss_connectioncatalogid: string;
  oss_connectionid?: string;
  oss_connectorname?: string;
  oss_environmentid?: string;
  oss_isserviceaccount?: boolean;
  oss_lastseenon?: string;
  oss_missingsince?: string;
  oss_name?: string;
  oss_ownername?: string;
  oss_ownerobjectid?: string;
  oss_ownerupn?: string;
  oss_status?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_connectioncatalogsstatecode;
  statuscode?: Oss_connectioncatalogsstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_connectioncatalogs extends Oss_connectioncatalogsBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  oss_isserviceaccountname?: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}