/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */
export const Oss_deploymentpipelinesstatecode = {
  0: 'Active',
  1: 'Inactive'
} as const;
export type Oss_deploymentpipelinesstatecode = keyof typeof Oss_deploymentpipelinesstatecode;
export const Oss_deploymentpipelinesstatuscode = {
  1: 'Active',
  2: 'Inactive'
} as const;
export type Oss_deploymentpipelinesstatuscode = keyof typeof Oss_deploymentpipelinesstatuscode;

export interface Oss_deploymentpipelinesBase {
  importsequencenumber?: number;
  oss_deploymentpipelineid: string;
  oss_name?: string;
  overriddencreatedon?: string;
  ownerid: string;
  owneridtype: string;
  statecode: Oss_deploymentpipelinesstatecode;
  statuscode?: Oss_deploymentpipelinesstatuscode;
  timezoneruleversionnumber?: number;
  utcconversiontimezonecode?: number;
}

export interface Oss_deploymentpipelines extends Oss_deploymentpipelinesBase {
  createdbyname?: string;
  createdbyyominame: string;
  createdon?: string;
  createdonbehalfbyname?: string;
  createdonbehalfbyyominame: string;
  modifiedbyname?: string;
  modifiedbyyominame: string;
  modifiedon?: string;
  modifiedonbehalfbyname?: string;
  modifiedonbehalfbyyominame: string;
  owneridname: string;
  owneridyominame: string;
  owningbusinessunitname: string;
  statecodename?: string;
  statuscodename?: string;
  versionnumber?: number;
  createdby?: object;
  _createdby_value?: string;
  createdonbehalfby?: object;
  _createdonbehalfby_value?: string;
  modifiedby?: object;
  _modifiedby_value?: string;
  modifiedonbehalfby?: object;
  _modifiedonbehalfby_value?: string;
  owningbusinessunit?: object;
  _owningbusinessunit_value?: string;
  owningteam?: object;
  _owningteam_value?: string;
  owninguser?: object;
  _owninguser_value?: string;
}