/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

export interface ResourceArray_ApiWithoutConnectionParameters {
  value?: ApiWithoutConnectionParameters[];
}

export interface ResourceArray_ConnectionWithoutConnectionParameters {
  value?: ConnectionWithoutConnectionParameters[];
}

export interface ResourceArray_Environment {
  value?: Environment[];
}

export interface ResourceArray_AdminFlow {
  value?: AdminFlow[];
}

export interface ResourceArray_AdminFlowWithoutDefinition {
  value?: AdminFlowWithoutDefinition[];
}

export interface ResourceArray_FlowPermission {
  value?: FlowPermission[];
}

export type Object = object;

export interface ModifyFlowPermissionPayload {
  put?: FlowPermission_Add[];
  delete?: FlowPermission_Remove[];
}

export interface FlowPermission_Add {
  properties?: PermissionProperties_Add;
}

export interface PermissionProperties_Add {
  principal?: Principal_Add;
}

export type Principal_Addtype = 'User'|'Group';

export interface Principal_Add {
  id: string;
  type: Principal_Addtype;
}

export interface FlowPermission_Remove {
  properties?: PermissionProperties_Remove;
}

export interface PermissionProperties_Remove {
  principal?: Principal_Remove;
}

export type Principal_Removetype = 'User'|'Group';

export interface Principal_Remove {
  id: string;
  type: Principal_Removetype;
}

export interface FlowPermission {
  name?: string;
  properties?: PermissionProperties;
}

export type PermissionPropertiesroleName = 'Owner'|'CanEdit'|'CanView';

export interface PermissionProperties {
  roleName?: PermissionPropertiesroleName;
  principal?: Principal;
}

export type Principaltype = 'User'|'Group';

export interface Principal {
  id?: string;
  displayName?: string;
  email?: string;
  type?: Principaltype;
  tenantId?: string;
  userPrincipalName?: string;
  thumbnailPhoto?: string;
}

export interface Flow {
  name?: string;
  properties: FlowProperties;
}

export type FlowPropertiesstate = 'Started'|'Stopped';
export type FlowPropertiesinstallationStatus = 'NotApplicable'|'Uninstalled'|'Broken'|'Installed';

export interface FlowProperties {
  displayName: string;
  definition: {
  };
  state: FlowPropertiesstate;
  connectionReferences?: ConnectionReferencesDictionary;
  createdTime?: string;
  lastModifiedTime?: string;
  templateName?: string;
  flowTriggerUri?: string;
  installationStatus?: FlowPropertiesinstallationStatus;
}

export interface FlowListCallbackUrlResponse {
  response: {
    value: string;
  };
}

export interface FlowWithConnectionReferences {
  name?: string;
  properties: FlowWithConnectionReferencesProperties;
}

export type FlowWithConnectionReferencesPropertiesstate = 'Started'|'Stopped';
export type FlowWithConnectionReferencesPropertiesinstallationStatus = 'NotApplicable'|'Uninstalled'|'Broken'|'Installed';

export interface FlowWithConnectionReferencesProperties {
  displayName: string;
  definition: {
  };
  state: FlowWithConnectionReferencesPropertiesstate;
  connectionReferences?: ConnectionReferencesArray;
  createdTime?: string;
  lastModifiedTime?: string;
  templateName?: string;
  flowTriggerUri?: string;
  installationStatus?: FlowWithConnectionReferencesPropertiesinstallationStatus;
  creator?: UserIdentity;
  definitionSummary?: DefinitionSummary;
}

export interface AdminFlow {
  name?: string;
  properties: AdminFlowProperties;
}

export interface AdminFlowWithoutDefinition {
  name?: string;
  properties: AdminFlowWithoutDefinitionProperties;
}

export type AdminFlowPropertiesstate = 'Started'|'Stopped';
export type AdminFlowPropertiesinstallationStatus = 'NotApplicable'|'Uninstalled'|'Broken'|'Installed';

export interface AdminFlowProperties {
  displayName: string;
  state: AdminFlowPropertiesstate;
  connectionReferences?: ConnectionReferencesDictionary;
  createdTime?: string;
  lastModifiedTime?: string;
  templateName?: string;
  flowTriggerUri?: string;
  installationStatus?: AdminFlowPropertiesinstallationStatus;
  creator?: UserIdentity;
  definitionSummary?: DefinitionSummary;
  estimatedSuspensionData?: EstimatedSuspensionData;
}

export type AdminFlowWithoutDefinitionPropertiesstate = 'Started'|'Stopped'|'Deleted'|'Suspended';

export interface AdminFlowWithoutDefinitionProperties {
  displayName: string;
  state?: AdminFlowWithoutDefinitionPropertiesstate;
  createdTime?: string;
  lastModifiedTime?: string;
}

export interface AdminFlowWithConnectionReferences {
  name?: string;
  properties: AdminFlowWithConnectionReferencesProperties;
}

export type AdminFlowWithConnectionReferencesPropertiesstate = 'Started'|'Stopped';
export type AdminFlowWithConnectionReferencesPropertiesinstallationStatus = 'NotApplicable'|'Uninstalled'|'Broken'|'Installed';

export interface AdminFlowWithConnectionReferencesProperties {
  displayName: string;
  state: AdminFlowWithConnectionReferencesPropertiesstate;
  connectionReferences?: ConnectionReferencesArray;
  createdTime?: string;
  lastModifiedTime?: string;
  templateName?: string;
  flowTriggerUri?: string;
  installationStatus?: AdminFlowWithConnectionReferencesPropertiesinstallationStatus;
  creator?: UserIdentity;
  definitionSummary?: DefinitionSummary;
}

export interface EstimatedSuspensionData {
  reason?: string;
  time?: string;
  powerAppPlanExcluded?: boolean;
}

export interface DefinitionSummary {
  triggers?: {
   _type?: string;
   kind?: string;
 }[];
  actions?: {
   _type?: string;
   swaggerOperationId?: string;
   api?: {
     name?: string;
     id?: string;
     _type?: string;
   };
 }[];
}

export interface UserIdentity {
  tenantId: string;
  objectId?: string;
  userId: string;
  userType: string;
}

export interface Environment {
  name?: string;
  location?: string;
  properties?: EnvironmentProperties;
}

export type EnvironmentPropertiesprovisioningState = 'NotSpecified'|'Succeeded'|'Deleting'|'Deleted'|'Failed'|'FailedDeleting';
export type EnvironmentPropertiescreationType = 'NotSpecified'|'Legacy'|'DefaultTenant'|'User'|'CommonDataModelLegacy'|'Partner'|'Developer';
export type EnvironmentPropertiesenvironmentSku = 'NotSpecified'|'Standard'|'Premium'|'Developer'|'Basic';
export type EnvironmentPropertiesenvironmentType = 'NotSpecified'|'Production'|'Sandbox';

export interface EnvironmentProperties {
  displayName?: string;
  description?: string;
  createdTime?: string;
  lastModifiedTime?: string;
  provisioningState?: EnvironmentPropertiesprovisioningState;
  creationType?: EnvironmentPropertiescreationType;
  environmentSku?: EnvironmentPropertiesenvironmentSku;
  environmentType?: EnvironmentPropertiesenvironmentType;
  isDefault?: boolean;
}

export type ApiConnectionParameters = object;

export interface Connection {
  name?: string;
  properties?: ConnectionProperties;
}

export interface ConnectionProperties {
  displayName?: string;
  apiId?: string;
  createdTime?: string;
  lastModifiedTime?: string;
  connectionParameters?: ApiConnectionParameters;
}

export interface Api {
  name?: string;
  properties?: ApiProperties;
}

export interface ApiProperties {
  displayName?: string;
  createdTime?: string;
  connectionParameters?: ApiConnectionParameters;
  primaryRuntimeUrl?: string;
  iconUri?: string;
}

export type ConnectionReferencesArray = ConnectionReference[];

export type ConnectionReferencesDictionary = object;

export interface ConnectionReference {
  connectionName?: string;
  displayName?: string;
  id: string;
  source?: string;
  connectionReferenceLogicalName?: string;
  apiDefinition?: ApiWithoutConnectionParameters;
}

export interface ApiWithoutConnectionParameters {
  name?: string;
  properties?: ApiPropertiesWithoutConnectionParameters;
}

export interface ApiPropertiesWithoutConnectionParameters {
  displayName?: string;
  createdTime?: string;
  primaryRuntimeUrl?: string;
  iconUri?: string;
  isCustomApi?: boolean;
  tier?: string;
}

export interface ConnectionWithoutConnectionParameters {
  name?: string;
  properties?: ConnectionPropertiesWithoutConnectionParameters;
}

export interface ConnectionPropertiesWithoutConnectionParameters {
  displayName?: string;
  apiId?: string;
  createdTime?: string;
  lastModifiedTime?: string;
}
